export const availableEmojisData = {
	'🥑': ['avocado', 'fruit', 'green', 'healthy', 'guacamole'],
	'🍼': ['baby', 'bottle', 'feeding', 'infant', 'formula'],
	'🥓': ['bacon', 'pork', 'breakfast', 'crispy', 'greasy'],
	'🥯': ['bagel', 'breakfast', 'bread', 'toasted', 'sesame'],
	'🥖': ['baguette', 'bread', 'french', 'loaf', 'crusty'],
	'🫘': ['beans', 'legume', 'protein', 'canned', 'bowl'],
	'🍺': ['beer', 'alcohol', 'brew', 'pint', 'bar'],
	'🍱': ['bento', 'lunch', 'box', 'meal', 'asian'],
	'🧃': ['juice', 'boxed', 'beverage', 'drink', 'fruit'],
	'🎂': ['cake', 'birthday', 'dessert', 'celebration', 'slice'],
	'🍾': ['champagne', 'bottle', 'celebration', 'pop', 'toast'],
	'🍞': ['bread', 'loaf', 'toast', 'sandwich', 'bakery'],
	'🥦': ['broccoli', 'vegetable', 'green', 'healthy', 'crunchy'],
	'🧋': ['bubble', 'tea', 'boba', 'drink', 'pearl'],
	'🌯': ['burrito', 'tortilla', 'wrap', 'mexican', 'filled'],
	'🍬': ['candy', 'sweets', 'chewy', 'lollipop', 'treat'],
	'🥫': ['canned', 'food', 'preserved', 'beans', 'soup'],
	'🧀': ['cheese', 'dairy', 'slice', 'melty', 'spread'],
	'🍫': ['chocolate', 'bar', 'cocoa', 'dessert', 'sweet'],
	'🥢': ['chopsticks', 'utensils', 'asian', 'eating', 'stick'],
	'🍻': ['beer', 'clink', 'cheers', 'toast', 'pub', 'drinks'],
	'🥂': ['glasses', 'cheers', 'toast', 'wine', 'celebrate'],
	'🍸': ['cocktail', 'alcohol', 'martini', 'glass', 'bar'],
	'🍚': ['rice', 'cooked', 'grain', 'side', 'staple'],
	'🍪': ['cookie', 'biscuit', 'bake', 'snack', 'chocolate', 'chip'],
	'🍳': ['cooking', 'frying', 'breakfast', 'eggs', 'pan'],
	'🥐': ['croissant', 'breakfast', 'pastry', 'buttery', 'french'],
	'🥤': ['cup', 'straw', 'soda', 'drink', 'beverage'],
	'🧁': ['cupcake', 'dessert', 'frosting', 'bake', 'party'],
	'🍛': ['curry', 'rice', 'spicy', 'indian', 'comfort'],
	'🍮': ['custard', 'flan', 'dessert', 'creamy', 'sweet'],
	'🥩': ['steak', 'meat', 'beef', 'grill', 'protein'],
	'🍡': ['dango', 'skewer', 'japanese', 'sweet', 'mochi'],
	'🍩': ['donut', 'doughnut', 'sweet', 'fried', 'glazed'],
	'🥟': ['dumpling', 'asian', 'steamed', 'filled', 'savory'],
	'🥚': ['egg', 'protein', 'breakfast', 'raw', 'boiled'],
	'🍆': ['eggplant', 'vegetable', 'purple', 'roasted', 'grill'],
	'🧆': ['falafel', 'vegan', 'chickpea', 'fried', 'middle', 'eastern'],
	'🍥': ['fish', 'cake', 'japanese', 'kamaboko', 'swirl', 'seafood'],
	'🫓': ['flatbread', 'wrap', 'naan', 'tortilla', 'bread'],
	'🫕': ['fondue', 'cheese', 'communal', 'dip', 'melting'],
	'🍽️': ['plate', 'cutlery', 'meal', 'tableware', 'dining'],
	'🥠': ['fortune', 'cookie', 'crispy', 'asian', 'dessert'],
	'🍟': ['fries', 'french', 'potato', 'snack', 'fast', 'food'],
	'🍤': ['fried', 'shrimp', 'seafood', 'tempura', 'fried'],
	'🥛': ['milk', 'drink', 'dairy', 'glass', 'calcium'],
	'🍏': ['apple', 'green', 'fruit', 'tart', 'healthy'],
	'🥗': ['salad', 'green', 'healthy', 'veggies', 'side'],
	'🍔': ['burger', 'hamburger', 'fast', 'food', 'beef', 'bun'],
	'☕': ['coffee', 'hot', 'drink', 'cafe', 'mug', 'espresso'],
	'🌭': ['hot', 'dog', 'sausage', 'bun', 'street', 'food', 'condiments'],
	'🌶️': ['chili', 'spicy', 'pepper', 'hot', 'sauce'],
	'🧊': ['ice', 'cold', 'cubes', 'drink', 'chill'],
	'🍨': ['ice', 'cream', 'sundae', 'frozen', 'dessert', 'scoop'],
	'🫙': ['jar', 'preserve', 'storage', 'glass', 'container'],
	'🥬': ['leafy', 'green', 'lettuce', 'veg', 'salad'],
	'🍋': ['lemon', 'citrus', 'tart', 'zest', 'fruit'],
	'🍭': ['lollipop', 'candy', 'sweets', 'stick', 'colorful'],
	'🥭': ['mango', 'tropical', 'fruit', 'juicy', 'ripe'],
	'🧉': ['mate', 'herbal', 'tea', 'south', 'america', 'shared'],
	'🍖': ['meat', 'on', 'bone', 'bbq', 'barbecue', 'roasted', 'protein'],
	'🍈': ['melon', 'fruit', 'green', 'sweet', 'summer'],
	'🥮': ['mooncake', 'asian', 'festival', 'sweet', 'pastry'],
	'🍢': ['oden', 'skewer', 'japanese', 'broth', 'street', 'food'],
	'🫒': ['olive', 'brine', 'mediterranean', 'oil', 'garnish'],
	'🥞': ['pancakes', 'stack', 'syrup', 'breakfast', 'fluffy'],
	'🥜': ['peanuts', 'nuts', 'snack', 'salty', 'allergy'],
	'🥧': ['pie', 'dessert', 'fruit', 'filling', 'crust'],
	'🍍': ['pineapple', 'tropical', 'fruit', 'sweet', 'tangy'],
	'🍕': ['pizza', 'slice', 'cheese', 'italian', 'pepperoni'],
	'🍿': ['popcorn', 'snack', 'movie', 'buttery', 'seasoned'],
	'🍲': ['stew', 'pot', 'soup', 'comfort', 'hot'],
	'🥔': ['potato', 'root', 'starch', 'mashed', 'roasted'],
	'🍗': ['poultry', 'leg', 'chicken', 'roasted', 'barbecue'],
	'🥨': ['pretzel', 'snack', 'salty', 'bakery', 'twist'],
	'🍎': ['apple', 'red', 'fruit', 'orchard', 'healthy'],
	'🍙': ['rice', 'ball', 'onigiri', 'japanese', 'portable', 'seaweed'],
	'🍘': ['rice', 'cracker', 'senbei', 'snack', 'crispy', 'japanese'],
	'🥪': ['sandwich', 'lunch', 'bread', 'stacked', 'filled'],
	'🍧': ['shaved', 'ice', 'snow', 'cone', 'icy', 'sweet', 'syrup'],
	'🍰': ['cake', 'dessert', 'slice', 'cream', 'celebration'],
	'🍦': ['soft', 'serve', 'ice', 'cream', 'cone', 'frozen', 'sweet'],
	'🍝': ['spaghetti', 'pasta', 'tomato', 'sauce', 'italian'],
	'🍜': ['ramen', 'steaming', 'bowl', 'noodles', 'broth', 'asian'],
	'🍓': ['strawberry', 'berry', 'red', 'fruit', 'summer'],
	'🥙': ['stuffed', 'flatbread', 'gyros', 'pita', 'wrap', 'mediterranean'],
	'🍣': ['sushi', 'sashimi', 'japanese', 'raw', 'rice'],
	'🌮': ['taco', 'mexican', 'shell', 'street', 'food', 'spicy'],
	'🥡': ['takeout', 'container', 'chinese', 'delivery', 'leftovers'],
	'🫔': ['tamale', 'masa', 'wrapped', 'mexican', 'steamed'],
	'🫖': ['teapot', 'tea', 'brew', 'ceramic', 'hot', 'drink'],
	'🍹': ['cocktail', 'tropical', 'drink', 'umbrella', 'bar'],
	'🥃': ['whiskey', 'neat', 'glass', 'spirit', 'bar'],
	'🧇': ['waffle', 'breakfast', 'grid', 'syrup', 'buttery'],
	'🍷': ['wine', 'red', 'glass', 'alcohol', 'vineyard']
} as const;

export type AvailableEmoji = keyof typeof availableEmojisData;
export const availableEmojis = Object.keys(availableEmojisData) as AvailableEmoji[];

export const emojiSearchList = Object.entries(availableEmojisData).map(([emoji, keywords]) => ({
	emoji,
	text: (keywords as readonly string[]).join(' ')
}));
