export const availableEmojisData = {
	'🏺': 'amphora',
	'🥑': 'avocado',
	'🍼': 'baby bottle',
	'🥓': 'bacon',
	'🥯': 'bagel',
	'🥖': 'baguette bread',
	'🍌': 'banana',
	'🫘': 'beans',
	'🍺': 'beer mug',
	'🫑': 'bell pepper',
	'🍱': 'bento box',
	'🧃': 'beverage box',
	'🎂': 'birthday cake',
	'🫐': 'blueberries',
	'🍾': 'bottle with popping cork',
	'🥣': 'bowl with spoon',
	'🍞': 'bread',
	'🥦': 'broccoli',
	'🍄‍🟫': 'brown mushroom',
	'🧋': 'bubble tea',
	'🌯': 'burrito',
	'🧈': 'butter',
	'🍬': 'candy',
	'🥫': 'canned food',
	'🥕': 'carrot',
	'🧀': 'cheese wedge',
	'🍒': 'cherries',
	'🌰': 'chestnut',
	'🍫': 'chocolate bar',
	'🥢': 'chopsticks',
	'🍻': 'clinking beer mugs',
	'🥂': 'clinking glasses',
	'🍸': 'cocktail glass',
	'🥥': 'coconut',
	'🍚': 'cooked rice',
	'🍪': 'cookie',
	'🍳': 'cooking',
	'🥐': 'croissant',
	'🥒': 'cucumber',
	'🥤': 'cup with straw',
	'🧁': 'cupcake',
	'🍛': 'curry rice',
	'🍮': 'custard',
	'🥩': 'cut of meat',
	'🍡': 'dango',
	'🍩': 'doughnut',
	'🥟': 'dumpling',
	'🌽': 'ear of corn',
	'🥚': 'egg',
	'🍆': 'eggplant',
	'🧆': 'falafel',
	'🍥': 'fish cake with swirl',
	'🫓': 'flatbread',
	'🫕': 'fondue',
	'🍴': 'fork and knife',
	'🍽️': 'fork and knife with plate',
	'🥠': 'fortune cookie',
	'🍟': 'french fries',
	'🍤': 'fried shrimp',
	'🧄': 'garlic',
	'🫚': 'ginger root',
	'🥛': 'glass of milk',
	'🍇': 'grapes',
	'🍏': 'green apple',
	'🥗': 'green salad',
	'🍔': 'hamburger',
	'🍯': 'honey pot',
	'☕': 'hot beverage',
	'🌭': 'hot dog',
	'🌶️': 'hot pepper',
	'🧊': 'ice',
	'🍨': 'ice cream',
	'🫙': 'jar',
	'🔪': 'kitchen knife',
	'🥝': 'kiwi fruit',
	'🥬': 'leafy green',
	'🍋': 'lemon',
	'🍋‍🟩': 'lime',
	'🍭': 'lollipop',
	'🥭': 'mango',
	'🧉': 'mate',
	'🍖': 'meat on bone',
	'🍈': 'melon',
	'🥮': 'moon cake',
	'🍢': 'oden',
	'🫒': 'olive',
	'🧅': 'onion',
	'🥞': 'pancakes',
	'🫛': 'pea pod',
	'🍑': 'peach',
	'🥜': 'peanuts',
	'🍐': 'pear',
	'🥧': 'pie',
	'🍍': 'pineapple',
	'🍕': 'pizza',
	'🍿': 'popcorn',
	'🍲': 'pot of food',
	'🥔': 'potato',
	'🍗': 'poultry leg',
	'🫗': 'pouring liquid',
	'🥨': 'pretzel',
	'🍎': 'red apple',
	'🍙': 'rice ball',
	'🍘': 'rice cracker',
	'🍠': 'roasted sweet potato',
	'🫜': 'root vegetable',
	'🍶': 'sake',
	'🧂': 'salt',
	'🥪': 'sandwich',
	'🥘': 'shallow pan of food',
	'🍧': 'shaved ice',
	'🍰': 'shortcake',
	'🍦': 'soft ice cream',
	'🍝': 'spaghetti',
	'🥄': 'spoon',
	'🍜': 'steaming bowl',
	'🍓': 'strawberry',
	'🥙': 'stuffed flatbread',
	'🍣': 'sushi',
	'🌮': 'taco',
	'🥡': 'takeout box',
	'🫔': 'tamale',
	'🍊': 'tangerine',
	'🍵': 'teacup without handle',
	'🫖': 'teapot',
	'🍅': 'tomato',
	'🍹': 'tropical drink',
	'🥃': 'tumbler glass',
	'🧇': 'waffle',
	'🍉': 'watermelon',
	'🍷': 'wine glass'
} as const;

export const availableEmojis = Object.keys(availableEmojisData);
